### ISSUE TITLE
Option to have a fixed page size

### ISSUE THREAD

**Issue by williamchang314** [PredixDev/px-data-table#123]
Hi Team,

I would like greater flexibility when using pagination controls on this component since I do not want the end-user to be able to have up to 100 rows per page. 

Currently, if I enable pagination, then there will be a dropdown allowing the user to select 10, 20, 50 or 100 rows per page. It would be very helpful if the component could allow customisation for rows-per-page options shown to the end-user i.e. the ability to add 5 rows per page as an option, or to remove some/all options for rows-per-page.

**Comment by randyaskin** [comment]
I've already added a pageSizeOptions property in order to cutover to a standard px-dropdown (right now it uses a regular select menu for pagination, which looks inconsistent in various browsers) as part of the component redesign. I will go ahead and expose it through to the main API. Should be available with the rest of the redesign components in June.

**Comment by randyaskin** [comment]
Fixed in v4.
