### ISSUE TITLE
if include-all-columns="false" the value is not getting set as false

### ISSUE THREAD

**Issue by ManjuKumar** [PredixDev/px-data-table#146]
Steps to reproduce:

1) use px-data-table and set the include-all-columns="false"

Expected output: the includeAllColumns should be equal to false
Actual output: while doing the unit testing of my components i found that px-data-table includeAllColumns is not getting set as false and returning true.

**Comment by benoitjchevalier** [comment]
This is an HTML specification that the presence of a boolean attribute represents `true` and the absence `false`: 
https://www.w3.org/TR/html5/infrastructure.html#boolean-attributes

don't include this attribute if you want it to be false since false is its default value. If you need to change it at runtime use javascript and change the property rather than the attribute (through the `set` API: `yourTable.set('includeAllColumns', false)`)
