### ISSUE TITLE
'formats' property does not exist

### ISSUE THREAD

**Issue by richardpineo** [PredixDev/px-data-table#159]
From the documentation, there is a 'formats' property that can be used to format data when rendering in the data table. There is no 'formats' property in the source code.

## Expected behavior and actual behavior:
Expected 'formats' to exist as a property. It did not.

## Steps to reproduce the problem:
N/A

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
px-data-table 4.0.12

**Comment by randyaskin** [comment]
As stated in the documentation:
```
formats: Object = {}
Inherited from Polymer.AppLocalizeBehavior
```
It doesn't exist in the data-table component because it's inherited from [here](https://github.com/PolymerElements/app-localize-behavior/blob/master/app-localize-behavior.html#L177). It can be used with any strings that we are localizing in the data table, though I don't think it would make much sense to do so in this case since they're all simple strings.

A separate valid enhancement request would be to add support for formatting data in the table. We don't currently call `localize` on the data itself because we rely on the application to format and pass it in pre-localized.

**Comment by richardpineo** [comment]
Ah okay, I think I understand. 

Is there a reason to inherit the AppLocalizeBehavior at all? My understanding from what you say is that it's not used in px-data-table automatically but is provided as a convenience for a client of px-data-table. 

This feels to me like noise - since any localization done for the strings being displayed in the table is done outside of the component, why inherit the AppLocalizeBehavior?

**Comment by randyaskin** [comment]
We use app-localize-behavior to provide localization support for all of the hardcoded strings in the data-table component - listed [here](https://www.predix-ui.com/#/develop/localizable-strings) - things like "Rows per page." We don't use app-localize-behavior on the *data* passed into the table.

**Comment by richardpineo** [comment]
Thank you! 
I didn't realize was the behavior but it makes sense.
