### ISSUE TITLE
px-data-table-column  : Documentation and explicit assignment

### ISSUE THREAD

**Issue by infactamente** [PredixDev/px-data-table#60]
type="dropdown" dropdown-items='[{"key":"one","val":"Mike"},{"key":"two","val":"Maria"},{"key":"three","val":"Wei"}]'

Please provide list of various different 'type'

and also a way to have different drop down for different row.

**Comment by randyaskin** [comment]
I've updated the code comments / [API documentation](http://predixdev.github.io/predix-ui/?show=px-data-table&type=component) for px-data-table-column to reflect all three `type` options (string, html, dropdown). 

We'll have to think about your enhancement request, I'm not sure how we would go about making the dropdown options dynamic by row, since everything except the table-data is column-based rather than row-based.

**Comment by mdwragg** [comment]
It's hard to imagine the use case with such a short description, please elaborate further what you are trying to achieve. I'm going to close this for now, if I'm guessing what you are trying to do, it would be pretty hard to achieve and would require us embedding meta data for each cell into the data itself. Which would be slow/painful/API breaking.
