### ISSUE TITLE
Need a way to turn off column sorting without defining all the columns

### ISSUE THREAD

**Issue by leebickmtu** [PredixDev/px-data-table#65]
The behavior right now enables sorting for all columns when 'table-data' is set without defining any 'px-data-table-column'.

If you want to disable all table sorting that mean defining all columns with an explicit 'px-data-table-column' and disabling sorting for each.

There should be a way to at the 'px-data-table' level disable all sorting.

Also, since the default on 'px-data-table-column' is sortable:false, I would expect sorting to be fully disabled across all columns when not specifying any 'px-data-table-column'.

**Comment by randyaskin** [comment]
Fixed in 2.0.0. Sortable is now a global property for the table, in addition to a property on each column. It's true on the table by default, just because that was the behavior before and I didn't want to break the API too much, but setting it false will disable across the board. If you don't specify it for a given column, and you use include-all-columns, it will pick up the table default. Hopefully that makes sense!
